[config]
[templates.qs]
input_path = "~/.config/matugen-themes/templates/quickshell.qml"
output_path = "~/.config/quickshell/theme/Theme.qml"
[templates.hypr]
input_path = "~/.config/matugen-themes/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/configuration/colors.lua"
